zookeeper:
  image: jplock/zookeeper
  hostname: zookeeper
  expose:
   - 2181
   - 2888 
   - 3888
  cpu_shares: 128
  mem_limit: 512M   
master:
  image: tmetsch/mesos_docker
  hostname: master
  ports:
   - 5050:5050
  links:
   - zookeeper:zookeeper
  environment:
   - MESOS_ZK=zk://zookeeper:2181/mesos
   - MESOS_IP=0.0.0.0
   - MESOS_WORK_DIR=/var/lib/mesos
   - MESOS_QUORUM=1
  command: /usr/local/sbin/mesos-master
  cpu_shares: 128
  mem_limit: 512M
marathon:
  image: tmetsch/mesos_docker
  hostname: marathon
  ports:
   - 8080:8080
  links:
   - master:master
   - zookeeper:zookeeper
  environment:
   - MARATHON_MASTER=zk://zookeeper:2181/mesos
   - MARATHON_ZK=zk://zookeeper:2181/marathon
   - MARATHON_MAX_TASKS_PER_OFFER=10
   - MARATHON_DISABLE_HA
  command: /opt/marathon/bin/start
  cpu_shares: 128
  mem_limit: 512M
node1:
  build: .
  links:
   - master:master
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /run:/run
  environment:
   - MESOS_MASTER=master:5050
   - MESOS_WORK_DIR=/tmp/mesos
   - MESOS_NO-SYSTEMD_ENABLE_SUPPORT
  command: /usr/local/sbin/mesos-slave
  privileged: true
  cpu_shares: 128
  mem_limit: 1G
#nodedocky:
#  image: tmetsch/mesos_docker
#  links:
#   - master:master
#  volumes:
#   - /sys/fs/cgroup:/sys/fs/cgroup
#   - /usr/bin/docker:/usr/bin/docker
#   - /var/run/docker.sock:/var/run/docker.sock
#  environment:
#   - MESOS_MASTER=master:5050
#   - MESOS_CONTAINERIZERS=docker
#   - MESOS_ATTRIBUTES=docker:true
#   - MESOS_RESOURCES=ports(*):[20000-32000]
#   - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=10mins
#   - MESOS_WORK_DIR=/tmp/mesos
#   - MESOS_NO-SYSTEMD_ENABLE_SUPPORT
#  command: /usr/local/sbin/mesos-slave
#  privileged: true
#  cpu_shares: 256
#  mem_limit: 1G
openlavamaster:
  build: .
  expose:
   - 6322/udp
   - 6322/tcp
   - 6323
   - 6324
   - 6325
  ports:
   - 9876:9876
  links:
   - master:master
  working_dir: /tmp/
  command: python2.7 mesoslava/framework.py
  cpu_shares: 128
  mem_limit: 512M

