version: '3'
services:
  zookeeper:
    image: jplock/zookeeper
    hostname: zookeeper
    expose:
     - 2181
     - 2888
     - 3888
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  master:
    image: tmetsch/mesos_docker
    hostname: master
    ports:
     - 5050:5050
    links:
     - zookeeper:zookeeper
    environment:
     - MESOS_ZK=zk://zookeeper:2181/mesos
     - MESOS_IP=0.0.0.0
     - MESOS_WORK_DIR=/var/lib/mesos
     - MESOS_QUORUM=1
     - MESOS_HOSTNAME=localhost
    command: /usr/local/sbin/mesos-master
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  marathon:
    image: tmetsch/mesos_docker
    hostname: marathon
    ports:
     - 8080:8080
    links:
     - master:master
     - zookeeper:zookeeper
    environment:
     - MESOS_NATIVE_JAVA_LIBRARY=/usr/local/lib/libmesos.so
     - MARATHON_MASTER=zk://zookeeper:2181/mesos
     - MARATHON_ZK=zk://zookeeper:2181/marathon
     - MARATHON_DISABLE_HA
    command: /opt/marathon/bin/marathon
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  node:
    build: .
    links:
     - master:master
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - /usr/bin/docker:/usr/bin/docker
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - MESOS_MASTER=master:5050
     - MESOS_WORK_DIR=/tmp/mesos
     - MESOS_SYSTEMD_ENABLE_SUPPORT=false
    command: /usr/local/sbin/mesos-slave
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  gpu_node:
    build: .
    links:
     - master:master
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - /usr/bin/docker:/usr/bin/docker
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - MESOS_MASTER=master:5050
     - MESOS_WORK_DIR=/tmp/mesos
     - MESOS_SYSTEMD_ENABLE_SUPPORT=false
     - MESOS_RESOURCES=cpus:4;gpus:1;mem:8192;disk:10240;ports:[30000-34000]
    command: /usr/local/sbin/mesos-slave
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  openlavamaster:
    build: .
    expose:
     - 6322/udp
     - 6322/tcp
     - 6323
     - 6324
     - 6325
    ports:
     - 9876:9876
    links:
     - master:master
    working_dir: /tmp/
    command: /tmp/scheduler.py
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
